comments:
  AbsentOrWrongFileLicense:
    active: false

complexity:
  CyclomaticComplexMethod:
    allowedComplexity: 40
  LongMethod:
    allowedLines: 120
  NestedBlockDepth:
    allowedDepth: 6

# Formatting rules are implemented via the ktlint plugin. As ktlint does not allow exceptions, we need to disable
# respective rules completely.
ktlint:
  ChainMethodContinuation:
    active: false
  ClassSignature:
    active: false
  ImportOrdering:
    active: false
  Indentation:
    active: false
  MaximumLineLength:
    active: false
  NoBlankLineInList:
    active: false
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: false
  TrailingCommaOnCallSite:
    active: true
    useTrailingCommaOnCallSite: false
  TrailingCommaOnDeclarationSite:
    active: true
    useTrailingCommaOnDeclarationSite: false

naming:
  InvalidPackageDeclaration:
    active: false

style:
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5
  ForbiddenComment:
    active: false
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2
  MagicNumber:
    active: false
  ReturnCount:
    max: 10
  ThrowsCount:
    max: 4
  WildcardImport:
    excludeImports:
      - dev.schuberth.stan.exporters.*
      - dev.schuberth.stan.parsers.*
