comments:
  AbsentOrWrongFileLicense:
    active: false

complexity:
  CyclomaticComplexMethod:
    threshold: 40
  LongMethod:
    threshold: 120
  NestedBlockDepth:
    threshold: 6

# Formatting rules are implemented via the ktlint plugin. As ktlint does not allow exceptions, we need to disable
# respective rules completely.
formatting:
  ImportOrdering:
    active: false
  Indentation:
    active: false
  MaximumLineLength:
    active: false
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: false

naming:
  InvalidPackageDeclaration:
    active: false

style:
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5
  ForbiddenComment:
    active: false
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2
  MagicNumber:
    active: false
  ReturnCount:
    max: 10
  ThrowsCount:
    max: 4
  WildcardImport:
    excludeImports:
      - dev.schuberth.stan.exporters.*
      - dev.schuberth.stan.parsers.*
